[package]
name = "upgate-planning"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true

[lints]
workspace = true

[dependencies]
pep440_rs = "0.7.3"
semver = "1.0.28"
upgate-domain = { version = "0.1.1", path = "../upgate-domain" }
