[package]
name = "upgate-audit"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true

[lints]
workspace = true

[dependencies]
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
upgate-domain = { version = "0.1.0", path = "../upgate-domain" }
upgate-infra = { version = "0.1.0", path = "../upgate-infra" }
