[package]
name = "upnow-presentation"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
upnow-domain = { path = "../upnow-domain" }
upnow-execution = { path = "../upnow-execution" }
upnow-planning = { path = "../upnow-planning" }
