[package]
name = "upgate"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true

[lints]
workspace = true

[[bin]]
name = "upgate"
path = "src/main.rs"

[dependencies]
clap = { version = "4.6.6", features = ["derive"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
toml = "1.1.4"
toml_edit = "0.25.13"
upgate-audit = { version = "0.1.1", path = "../upgate-audit" }
upgate-domain = { version = "0.1.1", path = "../upgate-domain" }
upgate-execution = { version = "0.1.1", path = "../upgate-execution" }
upgate-infra = { version = "0.1.1", path = "../upgate-infra" }
upgate-managers = { version = "0.1.1", path = "../upgate-managers" }
upgate-planning = { version = "0.1.1", path = "../upgate-planning" }
upgate-presentation = { version = "0.1.1", path = "../upgate-presentation" }
