[package]
name = "upnow-managers"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
chrono = { version = "0.4", default-features = false, features = ["clock"] }
flate2 = { version = "1.0", default-features = false, features = ["rust_backend"] }
pep440_rs = "0.7"
semver = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8"
upnow-domain = { path = "../upnow-domain" }
upnow-execution = { path = "../upnow-execution" }
upnow-infra = { path = "../upnow-infra" }
upnow-release = { path = "../upnow-release" }

[dev-dependencies]
